services:
  portainer-ce:
    ports:
      - 9443:9443
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - C:\Users\FOAPGenérico\Documents\docker\portainer\portainer_data:/data
    image: portainer/portainer-ce:latest